### ISSUE TITLE
Update the Altivec/VSX to be on par with the other accelerated architectures

### ISSUE THREAD

**Issue by lu-zero** [lu-zero/x264#4]
- [ ] prepare a list of functions not implemented
- for each of them
  - [ ] implement it when feasible
  - [ ] measure the actual speedup

**Comment by sasshka** [comment]
**functions** implemented for x86 SIMD but missing for ppc
the numbers are speed ups vs C code
**dct**:
- [ ] dct4x4dc sse2: 2 - speed up  ~1 expected, won't be implemented
- [ ] idct4x4dc sse2: 2 - minimal speed up expected - won't be implemented
- [ ] dct2x4 sse2: 1 - no speed up expected, won't be implemented
- [x] add8x8_idct_dc sse2: 10, ppc:  6
- [x] add16x16_idct_dc sse2: 12, ppc:13
- [x] sub8x8_dct_dc sse2: 4, ppc: 2
- [x] zigzag_scan_8x8_frame sse2: 2, ppc: 1.25 
- [ ] zigzag_scan_8x8_field  sse2: 2 - minimal speed up expected, won't be implemented
- [x] zigzag_interleave_8x8_cavlc sse2:3, ppc: 4x

https://github.com/sasshka/x264/tree/dct

**Comment by sasshka** [comment]
**mc**:
the first number is approximate speed up for x86 SIMD versions
- [x] plane_copy_swap_core                 2 --> implemented with 5.2 speed up
- [x] plane_copy_interleave_core          2 --> 3
- [x] store_interleave_chroma                5 --> 3.6
- [x] plane_copy_deinterleave               6 --> 8
- [x] load_deinterleave_chroma_fenc    3 -->  2
- [ ] load_deinterleave_chroma_fdec    3
- [x] plane_copy_deinterleave_rgb        3 -- > 4
- [x] plane_copy_deinterleave_v210     4x for LE and 5x for BE
- [x] the C code for v210 was fixed to work on BE correctly
- [ ] mbtree_fix8_pack 6
- [ ] mbtree_fix8_unpack 4
- [ ] mbtree_propagate_cost 4.5
- [ ] mbtree_propagate_list 2

**Comment by mc** [comment]
mhmhm. not sure where i can help you?

**Comment by lu-zero** [comment]
@sasshka typoed MC somehow I think.

**Comment by JulianVolodia** [comment]
@sasshka still working on this? Issue is still fresh enought?

**Comment by sasshka** [comment]
yes, I'm still working on that

**Comment by mrveera** [comment]
Any update, @sasshka are you still working on it?

**Comment by mamonet** [comment]
I've created [pull request in x264 repository](https://code.videolan.org/videolan/x264/-/merge_requests/43) that fulfill this issue, do I need to make a pull request with the changes here?
BTW I used an account with same username to not be confused.

**Comment by ghost** [comment]
You should ping @lu-zero, though it seems that this repo here is not up-to-date

(@lu-zero, maybe a tiny note pointing to the new repo would clarify things)

**Comment by lu-zero** [comment]
I had been busy, sending the pr to the main repository is good,

**Comment by abebeos** [comment]
@lu-zero, any updates on this? It looks that there is a functional patch: https://code.videolan.org/videolan/x264/-/merge_requests/43#note_74554

**Comment by lu-zero** [comment]
Is up to x264 upstream decide :)

**Comment by jittygitty** [comment]
@mamonet Unless I'm mistaken, this issue had a payable "Bounty" on it from IBM? see https://app.bountysource.com/issues/38471802-update-the-altivec-vsx-to-be-on-par-with-the-other-accelerated-architectures

**Comment by clin1234** [comment]
Is this bounty still open for reward from BountySource?

**Comment by malvanos** [comment]
Hi @clin1234, the BountySource is still up, but we have to sign the Contributor License Agreement to merge with master. This is blocking issue and we cannot commit anything to the official repository.

**Comment by ghost** [comment]
> but we have to sign the Contributor License Agreement to merge with master

@mamonet
